# Generated by Django 5.2 on 2025-07-28 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('commune', models.CharField(max_length=100)),
                ('fokontany', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Magasin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_magasin', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo_magasin')),
                ('lien_page_facebook', models.CharField()),
                ('precision_adresse', models.CharField(blank=True, max_length=150, null=True)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('adresse_magasin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendeur.adresse')),
                ('vendeur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='magasin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ModeleLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('delai_livraison_generale', models.CharField(max_length=100)),
                ('calcul_par', models.CharField(choices=[('lanja', 'lanja'), ('isa', 'isa')], default='isa', max_length=10)),
                ('gratuit_a_partir_de_prix', models.IntegerField(blank=True, help_text='Montant minimum pour la livraison gratuite', null=True)),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendeur.magasin')),
            ],
            options={
                'unique_together': {('magasin', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='HorsZoneLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frais_base', models.IntegerField()),
                ('unite_supplement', models.IntegerField()),
                ('frais_par_supplement', models.IntegerField(blank=True, null=True)),
                ('delai_livraison_horszone', models.CharField(max_length=100)),
                ('modele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horszones', to='vendeur.modelelivraison')),
            ],
        ),
        migrations.CreateModel(
            name='Produits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_produit', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=180)),
                ('moq', models.IntegerField(default=1)),
                ('image_profil_produit', models.ImageField(upload_to='image_profil_produit')),
                ('mot_clet', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='vendeur.magasin')),
                ('modele_livraison', models.ForeignKey(help_text='frais de livraison appliqué à ce produit', null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendeur.modelelivraison')),
            ],
        ),
        migrations.CreateModel(
            name='DetailleProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detaille_image', models.ImageField(upload_to='detaille_produit')),
                ('detaille_file', models.FileField(blank=True, null=True, upload_to='detaille_video')),
                ('detaille_produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailleproduit', to='vendeur.produits')),
            ],
        ),
        migrations.CreateModel(
            name='VariationProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_variation', models.CharField(max_length=100)),
                ('image_variation', models.ImageField(blank=True, null=True, upload_to='image_variation')),
                ('prix', models.IntegerField()),
                ('stock', models.PositiveIntegerField(default=0)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='vendeur.produits')),
            ],
        ),
        migrations.CreateModel(
            name='ZoneLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frais_base', models.IntegerField()),
                ('frais_par_supplement', models.IntegerField(blank=True, null=True)),
                ('delai_livraison_zone', models.CharField(max_length=100)),
                ('unite_supplement', models.IntegerField()),
                ('adresse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendeur.adresse')),
                ('modele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='vendeur.modelelivraison')),
            ],
            options={
                'unique_together': {('modele', 'adresse')},
            },
        ),
    ]
