# Generated by Django 5.2 on 2025-08-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendeur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produits',
            name='promo_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produits',
            name='promo_debut',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produits',
            name='promo_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produits',
            name='reduction_pourcentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pourcentage de réduction (0-100)', max_digits=5, null=True),
        ),
    ]
