# Generated by Django 5.2 on 2025-08-08 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendeur', '0002_produits_promo_active_produits_promo_debut_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdresseAcheteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_adresse', models.CharField(blank=True, max_length=100, null=True)),
                ('est_defaut', models.BooleanField(default=False)),
                ('adresse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendeur.adresse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
