# Generated by Django 5.2 on 2025-08-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acheteur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adresseacheteur',
            name='precision_adresse',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
